[profile.default]
src = "src"
out = "out"
libs = ["lib"]

optimizer = true
optimizer_runs = 200
viaIR = true

# Snapshot config
ffi = true
fs_permissions = [
  { access = "read-write", path = ".forge-snapshots/"}
]


# See more config options https://github.com/foundry-rs/foundry/tree/master/config